### ISSUE TITLE
Alert modification for email and password input verification 

### ISSUE THREAD

**Issue by tasnimahmed11** [agiledev-students-fall2022/final-project-team-resow#191]
### Tasks to do: 
- [ ] If the password is incorrect show an alert (login)
- [ ] If the email address is not in the database show an alert (login)
- [ ] check during registration if the user already exists or not (with email address)
- [ ] look into express-validator module
